version: '3.8'

services:
  frontend:
    build: ./frontend
    ports: ["80:80"]
    
  backend: 
    build: ./backend
    ports: ["8080:8080"]
    
  prometheus:
    image: prom/prometheus
    ports: ["9090:9090"]
    
  grafana:
    image: grafana/grafana
    ports: ["3000:3000"]